// Mocks generated by Mockito 5.4.6 from annotations
// in prestamos_app/test/reproduction_bug_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:prestamos_app/data/models/billing_cycle.dart' as _i5;
import 'package:prestamos_app/data/models/loan.dart' as _i4;
import 'package:prestamos_app/data/models/payment.dart' as _i3;
import 'package:prestamos_app/data/models/payment_allocation.dart' as _i9;
import 'package:prestamos_app/data/models/payment_plan.dart' as _i14;
import 'package:prestamos_app/data/repositories/billing_cycle_repository.dart'
    as _i12;
import 'package:prestamos_app/data/repositories/loan_repository.dart' as _i11;
import 'package:prestamos_app/data/repositories/payment_plan_repository.dart'
    as _i13;
import 'package:prestamos_app/data/repositories/payment_repository.dart' as _i7;
import 'package:prestamos_app/services/interest_calculation_service.dart'
    as _i6;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayment_1 extends _i1.SmartFake implements _i3.Payment {
  _FakePayment_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoan_2 extends _i1.SmartFake implements _i4.Loan {
  _FakeLoan_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBillingCycle_3 extends _i1.SmartFake implements _i5.BillingCycle {
  _FakeBillingCycle_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentDistribution_4 extends _i1.SmartFake
    implements _i6.PaymentDistribution {
  _FakePaymentDistribution_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoanCalculationResult_5 extends _i1.SmartFake
    implements _i6.LoanCalculationResult {
  _FakeLoanCalculationResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PaymentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentRepository extends _i1.Mock implements _i7.PaymentRepository {
  MockPaymentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i8.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i8.Future<_i2.Database>);

  @override
  _i8.Future<List<_i3.Payment>> getAllPayments() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPayments, []),
            returnValue: _i8.Future<List<_i3.Payment>>.value(<_i3.Payment>[]),
          )
          as _i8.Future<List<_i3.Payment>>);

  @override
  _i8.Future<_i3.Payment?> getPaymentById(String? paymentId) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentById, [paymentId]),
            returnValue: _i8.Future<_i3.Payment?>.value(),
          )
          as _i8.Future<_i3.Payment?>);

  @override
  _i8.Future<List<_i3.Payment>> getPaymentsByLoanId(String? loanId) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentsByLoanId, [loanId]),
            returnValue: _i8.Future<List<_i3.Payment>>.value(<_i3.Payment>[]),
          )
          as _i8.Future<List<_i3.Payment>>);

  @override
  _i8.Future<List<_i3.Payment>> getPaymentsByCustomerId(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentsByCustomerId, [customerId]),
            returnValue: _i8.Future<List<_i3.Payment>>.value(<_i3.Payment>[]),
          )
          as _i8.Future<List<_i3.Payment>>);

  @override
  _i8.Future<List<_i3.Payment>> getPaymentsByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentsByDateRange, [startDate, endDate]),
            returnValue: _i8.Future<List<_i3.Payment>>.value(<_i3.Payment>[]),
          )
          as _i8.Future<List<_i3.Payment>>);

  @override
  _i8.Future<List<_i3.Payment>> getTodayPayments() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayPayments, []),
            returnValue: _i8.Future<List<_i3.Payment>>.value(<_i3.Payment>[]),
          )
          as _i8.Future<List<_i3.Payment>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getPaymentsWithDetails({
    String? loanId,
    String? customerId,
    DateTime? fromDate,
    DateTime? toDate,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentsWithDetails, [], {
              #loanId: loanId,
              #customerId: customerId,
              #fromDate: fromDate,
              #toDate: toDate,
              #limit: limit,
            }),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getAllPaymentsWithCustomer() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPaymentsWithCustomer, []),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<_i3.Payment> insertPaymentWithAllocations(
    _i3.Payment? payment,
    List<_i9.PaymentAllocation>? allocations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertPaymentWithAllocations, [
              payment,
              allocations,
            ]),
            returnValue: _i8.Future<_i3.Payment>.value(
              _FakePayment_1(
                this,
                Invocation.method(#insertPaymentWithAllocations, [
                  payment,
                  allocations,
                ]),
              ),
            ),
          )
          as _i8.Future<_i3.Payment>);

  @override
  _i8.Future<_i3.Payment> insertPayment(_i3.Payment? payment) =>
      (super.noSuchMethod(
            Invocation.method(#insertPayment, [payment]),
            returnValue: _i8.Future<_i3.Payment>.value(
              _FakePayment_1(
                this,
                Invocation.method(#insertPayment, [payment]),
              ),
            ),
          )
          as _i8.Future<_i3.Payment>);

  @override
  _i8.Future<int> voidPayment(String? paymentId, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#voidPayment, [paymentId, reason]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> updateExchangeProfit(String? paymentId, double? profit) =>
      (super.noSuchMethod(
            Invocation.method(#updateExchangeProfit, [paymentId, profit]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<String> getNextReceiptNumber() =>
      (super.noSuchMethod(
            Invocation.method(#getNextReceiptNumber, []),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getNextReceiptNumber, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<_i9.PaymentAllocation>> getPaymentAllocations(
    String? paymentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentAllocations, [paymentId]),
            returnValue: _i8.Future<List<_i9.PaymentAllocation>>.value(
              <_i9.PaymentAllocation>[],
            ),
          )
          as _i8.Future<List<_i9.PaymentAllocation>>);

  @override
  _i8.Future<List<_i9.PaymentAllocation>> getAllAllocationsForLoan(
    String? loanId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllAllocationsForLoan, [loanId]),
            returnValue: _i8.Future<List<_i9.PaymentAllocation>>.value(
              <_i9.PaymentAllocation>[],
            ),
          )
          as _i8.Future<List<_i9.PaymentAllocation>>);

  @override
  _i8.Future<double> getTotalCollectedToday() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalCollectedToday, []),
            returnValue: _i8.Future<double>.value(0.0),
          )
          as _i8.Future<double>);

  @override
  _i8.Future<Map<String, double>> getTotalCollectedTodayByCurrency() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalCollectedTodayByCurrency, []),
            returnValue: _i8.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i8.Future<Map<String, double>>);

  @override
  _i8.Future<double> getCapitalRecoveredToday() =>
      (super.noSuchMethod(
            Invocation.method(#getCapitalRecoveredToday, []),
            returnValue: _i8.Future<double>.value(0.0),
          )
          as _i8.Future<double>);

  @override
  _i8.Future<Map<String, double>> getCapitalRecoveredTodayByCurrency() =>
      (super.noSuchMethod(
            Invocation.method(#getCapitalRecoveredTodayByCurrency, []),
            returnValue: _i8.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i8.Future<Map<String, double>>);

  @override
  _i8.Future<double> getTotalCollectedInRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalCollectedInRange, [startDate, endDate]),
            returnValue: _i8.Future<double>.value(0.0),
          )
          as _i8.Future<double>);

  @override
  _i8.Future<int> getPaymentCount({String? status}) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentCount, [], {#status: status}),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<double> getRealizedEarnings({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRealizedEarnings, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i8.Future<double>.value(0.0),
          )
          as _i8.Future<double>);

  @override
  _i8.Future<Map<String, double>> getRealizedEarningsByCurrency({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRealizedEarningsByCurrency, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i8.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i8.Future<Map<String, double>>);

  @override
  _i8.Future<String?> getMaxReceiptNumber() =>
      (super.noSuchMethod(
            Invocation.method(#getMaxReceiptNumber, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<_i3.Payment> registerRecoveryPayment({
    required _i3.Payment? payment,
    required List<_i9.PaymentAllocation>? allocations,
    required bool? restrictCustomer,
    required String? restrictionReason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerRecoveryPayment, [], {
              #payment: payment,
              #allocations: allocations,
              #restrictCustomer: restrictCustomer,
              #restrictionReason: restrictionReason,
            }),
            returnValue: _i8.Future<_i3.Payment>.value(
              _FakePayment_1(
                this,
                Invocation.method(#registerRecoveryPayment, [], {
                  #payment: payment,
                  #allocations: allocations,
                  #restrictCustomer: restrictCustomer,
                  #restrictionReason: restrictionReason,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.Payment>);
}

/// A class which mocks [LoanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoanRepository extends _i1.Mock implements _i11.LoanRepository {
  MockLoanRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i4.Loan>> getAllLoans() =>
      (super.noSuchMethod(
            Invocation.method(#getAllLoans, []),
            returnValue: _i8.Future<List<_i4.Loan>>.value(<_i4.Loan>[]),
          )
          as _i8.Future<List<_i4.Loan>>);

  @override
  _i8.Future<List<_i4.Loan>> getActiveLoans() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveLoans, []),
            returnValue: _i8.Future<List<_i4.Loan>>.value(<_i4.Loan>[]),
          )
          as _i8.Future<List<_i4.Loan>>);

  @override
  _i8.Future<_i4.Loan?> getLoanById(String? loanId) =>
      (super.noSuchMethod(
            Invocation.method(#getLoanById, [loanId]),
            returnValue: _i8.Future<_i4.Loan?>.value(),
          )
          as _i8.Future<_i4.Loan?>);

  @override
  _i8.Future<List<_i4.Loan>> getLoansByCustomerId(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getLoansByCustomerId, [customerId]),
            returnValue: _i8.Future<List<_i4.Loan>>.value(<_i4.Loan>[]),
          )
          as _i8.Future<List<_i4.Loan>>);

  @override
  _i8.Future<List<_i4.Loan>> getActiveLoansByCustomerId(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveLoansByCustomerId, [customerId]),
            returnValue: _i8.Future<List<_i4.Loan>>.value(<_i4.Loan>[]),
          )
          as _i8.Future<List<_i4.Loan>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getLoansWithCustomer({
    String? status,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLoansWithCustomer, [], {
              #status: status,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getConsolidatedActiveLoans() =>
      (super.noSuchMethod(
            Invocation.method(#getConsolidatedActiveLoans, []),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<_i4.Loan> insertLoan(_i4.Loan? loan) =>
      (super.noSuchMethod(
            Invocation.method(#insertLoan, [loan]),
            returnValue: _i8.Future<_i4.Loan>.value(
              _FakeLoan_2(this, Invocation.method(#insertLoan, [loan])),
            ),
          )
          as _i8.Future<_i4.Loan>);

  @override
  _i8.Future<String?> getMaxLoanNumber() =>
      (super.noSuchMethod(
            Invocation.method(#getMaxLoanNumber, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<int> updateLoan(_i4.Loan? loan) =>
      (super.noSuchMethod(
            Invocation.method(#updateLoan, [loan]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> updatePrincipalBalance(String? loanId, double? newBalance) =>
      (super.noSuchMethod(
            Invocation.method(#updatePrincipalBalance, [loanId, newBalance]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> closeLoan(String? loanId, String? closeStatus) =>
      (super.noSuchMethod(
            Invocation.method(#closeLoan, [loanId, closeStatus]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> deleteLoan(String? loanId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLoan, [loanId]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> getLoanCount({String? status}) =>
      (super.noSuchMethod(
            Invocation.method(#getLoanCount, [], {#status: status}),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> getOverdueLoanCount() =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueLoanCount, []),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<double> getTotalPrincipalBalance() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalPrincipalBalance, []),
            returnValue: _i8.Future<double>.value(0.0),
          )
          as _i8.Future<double>);

  @override
  _i8.Future<Map<String, double>> getTotalPrincipalBalanceByCurrency() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalPrincipalBalanceByCurrency, []),
            returnValue: _i8.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i8.Future<Map<String, double>>);

  @override
  _i8.Future<double> getTotalNormalizedPrincipalBalance(String? baseCurrency) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalNormalizedPrincipalBalance, [
              baseCurrency,
            ]),
            returnValue: _i8.Future<double>.value(0.0),
          )
          as _i8.Future<double>);

  @override
  _i8.Future<double> getTotalOriginalPrincipal() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalOriginalPrincipal, []),
            returnValue: _i8.Future<double>.value(0.0),
          )
          as _i8.Future<double>);

  @override
  _i8.Future<Map<String, double>> getTotalOriginalPrincipalByCurrency() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalOriginalPrincipalByCurrency, []),
            returnValue: _i8.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i8.Future<Map<String, double>>);

  @override
  _i8.Future<bool> hasPayments(String? loanId) =>
      (super.noSuchMethod(
            Invocation.method(#hasPayments, [loanId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<double> getProjectedMonthlyEarnings() =>
      (super.noSuchMethod(
            Invocation.method(#getProjectedMonthlyEarnings, []),
            returnValue: _i8.Future<double>.value(0.0),
          )
          as _i8.Future<double>);

  @override
  _i8.Future<Map<String, double>> getProjectedMonthlyEarningsByCurrency() =>
      (super.noSuchMethod(
            Invocation.method(#getProjectedMonthlyEarningsByCurrency, []),
            returnValue: _i8.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i8.Future<Map<String, double>>);

  @override
  _i8.Future<Map<String, dynamic>?> checkCustomerRestriction(
    String? customerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkCustomerRestriction, [customerId]),
            returnValue: _i8.Future<Map<String, dynamic>?>.value(),
          )
          as _i8.Future<Map<String, dynamic>?>);
}

/// A class which mocks [BillingCycleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBillingCycleRepository extends _i1.Mock
    implements _i12.BillingCycleRepository {
  MockBillingCycleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i5.BillingCycle>> getBillingCyclesByLoan(String? loanId) =>
      (super.noSuchMethod(
            Invocation.method(#getBillingCyclesByLoan, [loanId]),
            returnValue: _i8.Future<List<_i5.BillingCycle>>.value(
              <_i5.BillingCycle>[],
            ),
          )
          as _i8.Future<List<_i5.BillingCycle>>);

  @override
  _i8.Future<_i5.BillingCycle?> getBillingCycleById(String? billingCycleId) =>
      (super.noSuchMethod(
            Invocation.method(#getBillingCycleById, [billingCycleId]),
            returnValue: _i8.Future<_i5.BillingCycle?>.value(),
          )
          as _i8.Future<_i5.BillingCycle?>);

  @override
  _i8.Future<List<_i5.BillingCycle>> getPendingCyclesByLoan(String? loanId) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingCyclesByLoan, [loanId]),
            returnValue: _i8.Future<List<_i5.BillingCycle>>.value(
              <_i5.BillingCycle>[],
            ),
          )
          as _i8.Future<List<_i5.BillingCycle>>);

  @override
  _i8.Future<List<_i5.BillingCycle>> getOverdueCycles() =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueCycles, []),
            returnValue: _i8.Future<List<_i5.BillingCycle>>.value(
              <_i5.BillingCycle>[],
            ),
          )
          as _i8.Future<List<_i5.BillingCycle>>);

  @override
  _i8.Future<List<_i5.BillingCycle>> getCyclesDueToday() =>
      (super.noSuchMethod(
            Invocation.method(#getCyclesDueToday, []),
            returnValue: _i8.Future<List<_i5.BillingCycle>>.value(
              <_i5.BillingCycle>[],
            ),
          )
          as _i8.Future<List<_i5.BillingCycle>>);

  @override
  _i8.Future<List<_i5.BillingCycle>> getCyclesDueInRange(
    DateTime? startDate,
    DateTime? endDate, {
    String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCyclesDueInRange,
              [startDate, endDate],
              {#status: status},
            ),
            returnValue: _i8.Future<List<_i5.BillingCycle>>.value(
              <_i5.BillingCycle>[],
            ),
          )
          as _i8.Future<List<_i5.BillingCycle>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getCyclesWithDetails({
    DateTime? dueDate,
    bool? overdueOnly = false,
    String? frequency,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCyclesWithDetails, [], {
              #dueDate: dueDate,
              #overdueOnly: overdueOnly,
              #frequency: frequency,
            }),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<_i5.BillingCycle> insertBillingCycle(_i5.BillingCycle? cycle) =>
      (super.noSuchMethod(
            Invocation.method(#insertBillingCycle, [cycle]),
            returnValue: _i8.Future<_i5.BillingCycle>.value(
              _FakeBillingCycle_3(
                this,
                Invocation.method(#insertBillingCycle, [cycle]),
              ),
            ),
          )
          as _i8.Future<_i5.BillingCycle>);

  @override
  _i8.Future<void> insertBillingCycles(List<_i5.BillingCycle>? cycles) =>
      (super.noSuchMethod(
            Invocation.method(#insertBillingCycles, [cycles]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> updateBillingCycle(_i5.BillingCycle? cycle) =>
      (super.noSuchMethod(
            Invocation.method(#updateBillingCycle, [cycle]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> updateInterestPaid(
    String? billingCycleId,
    double? additionalPaid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateInterestPaid, [
              billingCycleId,
              additionalPaid,
            ]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> capitalizeCycle(
    String? billingCycleId,
    double? amountToCapitalize,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#capitalizeCycle, [
              billingCycleId,
              amountToCapitalize,
            ]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> deleteBillingCycle(String? billingCycleId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBillingCycle, [billingCycleId]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> deleteBillingCyclesByLoan(String? loanId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBillingCyclesByLoan, [loanId]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<double> getTotalPendingInterest(String? loanId) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalPendingInterest, [loanId]),
            returnValue: _i8.Future<double>.value(0.0),
          )
          as _i8.Future<double>);

  @override
  _i8.Future<int> getOverdueCycleCount() =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueCycleCount, []),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<_i5.BillingCycle?> getCurrentCycle(String? loanId) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentCycle, [loanId]),
            returnValue: _i8.Future<_i5.BillingCycle?>.value(),
          )
          as _i8.Future<_i5.BillingCycle?>);

  @override
  _i8.Future<_i5.BillingCycle?> getActiveCycle(
    String? loanId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveCycle, [loanId, date]),
            returnValue: _i8.Future<_i5.BillingCycle?>.value(),
          )
          as _i8.Future<_i5.BillingCycle?>);
}

/// A class which mocks [PaymentPlanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentPlanRepository extends _i1.Mock
    implements _i13.PaymentPlanRepository {
  MockPaymentPlanRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i14.PaymentPlan>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i8.Future<List<_i14.PaymentPlan>>.value(
              <_i14.PaymentPlan>[],
            ),
          )
          as _i8.Future<List<_i14.PaymentPlan>>);

  @override
  _i8.Future<List<_i14.PaymentPlan>> getActive() =>
      (super.noSuchMethod(
            Invocation.method(#getActive, []),
            returnValue: _i8.Future<List<_i14.PaymentPlan>>.value(
              <_i14.PaymentPlan>[],
            ),
          )
          as _i8.Future<List<_i14.PaymentPlan>>);

  @override
  _i8.Future<_i14.PaymentPlan?> getById(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [planId]),
            returnValue: _i8.Future<_i14.PaymentPlan?>.value(),
          )
          as _i8.Future<_i14.PaymentPlan?>);

  @override
  _i8.Future<List<_i14.PaymentPlan>> getPlansForCategory(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlansForCategory, [categoryId]),
            returnValue: _i8.Future<List<_i14.PaymentPlan>>.value(
              <_i14.PaymentPlan>[],
            ),
          )
          as _i8.Future<List<_i14.PaymentPlan>>);

  @override
  _i8.Future<void> insert(_i14.PaymentPlan? plan) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [plan]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> update(_i14.PaymentPlan? plan) =>
      (super.noSuchMethod(
            Invocation.method(#update, [plan]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> delete(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [planId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> hasActiveLoans(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#hasActiveLoans, [planId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> toggleActive(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleActive, [planId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [InterestCalculationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInterestCalculationService extends _i1.Mock
    implements _i6.InterestCalculationService {
  MockInterestCalculationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.PaymentDistribution calculatePaymentAllocation({
    required _i4.Loan? loan,
    required double? paymentAmount,
    required List<_i5.BillingCycle> pendingCycles,
    required String? paymentType,
    required bool? dailyAccrualEnabled,
    DateTime? paymentDate,
    String? recoveryPriority,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculatePaymentAllocation, [], {
              #loan: loan,
              #paymentAmount: paymentAmount,
              #pendingCycles: pendingCycles,
              #paymentType: paymentType,
              #dailyAccrualEnabled: dailyAccrualEnabled,
              #paymentDate: paymentDate,
              #recoveryPriority: recoveryPriority,
            }),
            returnValue: _FakePaymentDistribution_4(
              this,
              Invocation.method(#calculatePaymentAllocation, [], {
                #loan: loan,
                #paymentAmount: paymentAmount,
                #pendingCycles: pendingCycles,
                #paymentType: paymentType,
                #dailyAccrualEnabled: dailyAccrualEnabled,
                #paymentDate: paymentDate,
              }),
            ),
          )
          as _i6.PaymentDistribution);

  @override
  _i6.LoanCalculationResult calculateTotalDebt({
    required _i4.Loan? loan,
    required List<_i5.BillingCycle>? pendingCycles,
    required DateTime? paymentDate,
    required String? paymentType,
    required bool? dailyAccrualEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateTotalDebt, [], {
              #loan: loan,
              #pendingCycles: pendingCycles,
              #paymentDate: paymentDate,
              #paymentType: paymentType,
              #dailyAccrualEnabled: dailyAccrualEnabled,
            }),
            returnValue: _FakeLoanCalculationResult_5(
              this,
              Invocation.method(#calculateTotalDebt, [], {
                #loan: loan,
                #pendingCycles: pendingCycles,
                #paymentDate: paymentDate,
                #paymentType: paymentType,
                #dailyAccrualEnabled: dailyAccrualEnabled,
              }),
            ),
          )
          as _i6.LoanCalculationResult);

  @override
  double calculateMonthlyInterest(_i4.Loan? loan) =>
      (super.noSuchMethod(
            Invocation.method(#calculateMonthlyInterest, [loan]),
            returnValue: 0.0,
          )
          as double);

  @override
  double calculateBiweeklyInterest(_i4.Loan? loan) =>
      (super.noSuchMethod(
            Invocation.method(#calculateBiweeklyInterest, [loan]),
            returnValue: 0.0,
          )
          as double);

  @override
  double calculateDailyInterest(_i4.Loan? loan) =>
      (super.noSuchMethod(
            Invocation.method(#calculateDailyInterest, [loan]),
            returnValue: 0.0,
          )
          as double);
}
